<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="documentstructure" nsURI="http://www.eclipse.org/papyrus/model2doc/emf/1.0.0/documentstructure"
    nsPrefix="documentstructure">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="DocumentStructure"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TextDocument" eSuperTypes="#//Document">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainTitle" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textDocumentPart" ordered="false"
        upperBound="-1" eType="#//TextDocumentPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextDocumentPart" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Document" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentGeneratorConfiguration"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.model2doc.core.generatorconfiguration/model/generatorconfiguration.ecore#//IDocumentGeneratorConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" ordered="false"
        lowerBound="1" upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.model2doc.core.author/model/author.ecore#//IAuthor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="#//TextDocumentPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyPart" ordered="false"
        upperBound="-1" eType="#//BodyPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyPart" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" ordered="false"
        eType="#//DataSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This object is used to refer to the model object source providing the given part of the document."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//ComposedBodyPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComposedBodyPart" abstract="true" interface="true"
      eSuperTypes="#//BodyPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subBodyPart" ordered="false"
        upperBound="-1" eType="#//BodyPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Title" eSuperTypes="#//ComposedBodyPart">
    <eOperations name="getLevel" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//LeafBodyPart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This object represents an image inserted in the document."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imagePath" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The path can be in the user workspace in platform:/resource or, somewhere on the user computer, so for windows, it will be in C:/ for example."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The caption of the image."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeafBodyPart" abstract="true" interface="true"
      eSuperTypes="#//BodyPart"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFDataSource" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eobject" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableOfContents" eSuperTypes="#//TextDocumentPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tocTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Table Of Contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedBasicTable" eSuperTypes="../../org.eclipse.papyrus.model2doc.core.builtintypes/model/BuiltInTypes.ecore#//BasicTable #//LeafBodyPart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class extends the Table provided by the BuiltInTypes metamodel.&#xD;&#xA;Its allows us to have a common Table definition between DocumentStructure and the generator interface.&#xD;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedTextCell" eSuperTypes="../../org.eclipse.papyrus.model2doc.core.builtintypes/model/BuiltInTypes.ecore#//TextCell">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="We extends the TextCell provided by the BuiltInTypes metamodel, in order to be able to associate them a DataSource if required."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" ordered="false"
        eType="#//DataSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedBasicList" eSuperTypes="../../org.eclipse.papyrus.model2doc.core.builtintypes/model/BuiltInTypes.ecore#//BasicList #//LeafBodyPart"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedTextListItem" eSuperTypes="../../org.eclipse.papyrus.model2doc.core.builtintypes/model/BuiltInTypes.ecore#//TextListItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasource" ordered="false"
        eType="#//DataSource" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
