<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generatorconfiguration" nsURI="http://www.eclipse.org/papyrus/model2doc/1.0.0/generatorconfiguration"
    nsPrefix="generatorconfiguration">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="GeneratorConfiguration"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultDocumentStructureGeneratorConfiguration"
      eSuperTypes="#//AbstractDocumentStructureGeneratorConfiguration #//IDocumentStructureGeneratorConfiguration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Default implementation to define the Document Structure generator.&#xD;&#xA;These is no inheritance between DefaultDocumentGeneratorConfiguration and DefaultDocumentStructureGeneratorConfiguration, in order to constraint by type the kind of generator to use the the DocumentStructureTemplate and DocumentStructure models."/>
    </eAnnotations>
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="createDocumentStructureOutputAccessor"
          ordered="false" lowerBound="1" eType="#//IOutputFileAccessor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Return an accessor for the output Document Structure file."/>
          <details key="body" value="return new org.eclipse.papyrus.model2doc.core.generatorconfiguration.internal.accessors.DocumentStructureOutputFileAccessor(this);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IDocumentStructureGeneratorConfiguration/createDocumentStructureOutputAccessor"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="createDocumentGeneratorConfiguration"
          ordered="false" lowerBound="1" eType="#//IDocumentGeneratorConfiguration">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Creates a IDocumentGeneratorConfiguration from the current configuration."/>
          <details key="body" value="final DefaultDocumentGeneratorConfiguration newConf = GeneratorConfigurationFactory.eINSTANCE.createDefaultDocumentGeneratorConfiguration();&#xA;final Iterator&lt;EAttribute> iter = newConf.eClass().getEAllAttributes().iterator();&#xA;while (iter.hasNext()) {&#xA;&#x9;final EStructuralFeature feature = iter.next();&#xA;&#x9;newConf.eSet(feature, configuration.eGet(feature));&#xA;}&#xA;return newConf;"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IDocumentStructureGeneratorConfiguration/createDocumentGeneratorConfiguration"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="createImageOutputAccessor" ordered="false"
          lowerBound="1" eType="#//IOutputFileAccessor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Return an accessor for the output image files"/>
          <details key="body" value="return new org.eclipse.papyrus.model2doc.core.generatorconfiguration.internal.accessors.ImageOutputFileAccessor(this);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IDocumentStructureGeneratorConfiguration/createImageOutputAccessor"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDocumentStructureGeneratorConfiguration"
      abstract="true" eSuperTypes="#//AbstractDocumentGeneratorConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="structureGeneratorId" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyEditorFactory" value="editor://generatorconfiguration/AbstractDocumentStructureGeneratorConfiguration/structureGeneratorId/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageFolder" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The output image folder. It can be a full path (platform:/resource/projectName/...) or a path in the current plugin (generation/outputImageFolder, interpreted as platform:/resource/projectName/generation/outputImageFolder) or a system path (ex: c:\MyDocuments)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="structureFolder" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The output image folder. It can be a full path (platform:/resource/projectName/...) or a path in the current plugin (generation/outputImageFolder, interpreted as platform:/resource/projectName/generation/outputImageFolder).&#xD;&#xA;It can't be a system path (c:\myDocuments is not alloxed for example)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDocumentGeneratorConfiguration"
      abstract="true" eSuperTypes="#//IGeneratorConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saveDocumentStructure"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, the document structure model will be kept after the generation. If false, it will be destroyed."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saveImages" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, the generated images will be kept after the generation. If false, we will erase them."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateFile" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The path to the file to use as template. This file contains de style description and maybe the cover page too."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentName" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the document, without its extension."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentFolder" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The output folder. It can be a full path (platform:/resource/projectName/...) or a path in the current plugin (generation/outputFolder, interpreted as platform:/resource/projectName/generation/outputFolder), or a system path (ex: c:\MyDocuments)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentGeneratorId" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The identifier of the document generator to use."/>
        <details key="propertyEditorFactory" value="editor://generatorconfiguration/AbstractDocumentGeneratorConfiguration/documentGeneratorId/"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IGeneratorConfiguration" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Common interface for document generator configuration."/>
    </eAnnotations>
    <eOperations name="getDocumentName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getDocumentFolder" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getDocumentGeneratorId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setDocumentName" ordered="false" lowerBound="1">
      <eParameters name="documentName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDocumentStructureGeneratorConfiguration"
      abstract="true" interface="true" eSuperTypes="#//IGeneratorConfiguration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Common Interface to define the Document Structure generator in the model."/>
    </eAnnotations>
    <eOperations name="createDocumentGeneratorConfiguration" ordered="false" lowerBound="1"
        eType="#//IDocumentGeneratorConfiguration">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Creates a IDocumentGeneratorConfiguration from the current configuration."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getStructureGeneratorId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getImageFolder" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getStructureFolder" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="createDocumentStructureOutputAccessor" ordered="false" lowerBound="1"
        eType="#//IOutputFileAccessor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return an accessor for the output Document Structure file."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="createImageOutputAccessor" ordered="false" lowerBound="1" eType="#//IOutputFileAccessor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return an accessor for the output image files"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDocumentGeneratorConfiguration" abstract="true"
      interface="true" eSuperTypes="#//IGeneratorConfiguration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Common Interface to use to define the Document Generator Configuration."/>
    </eAnnotations>
    <eOperations name="isSaveDocumentStructure" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isSaveImages" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getTemplateFile" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="createTemplateFileInputAccessor" ordered="false" lowerBound="1"
        eType="#//IInputFileAccessor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return an accessor to get the template."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="createDocumentOutputAccessor" ordered="false" lowerBound="1"
        eType="#//IOutputFileAccessor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return an accessor for the generated output document."/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IInputFileAccessor" instanceClassName="org.eclipse.papyrus.model2doc.core.builtintypes.accessors.IInputFileAccessor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IOutputFileAccessor" instanceClassName="org.eclipse.papyrus.model2doc.core.generatorconfiguration.accessors.IOutputFileAccessor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultDocumentGeneratorConfiguration"
      eSuperTypes="#//AbstractDocumentGeneratorConfiguration #//IDocumentGeneratorConfiguration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Default implementation to define the DocumentGeneratorConfiguration.&#xD;&#xA;These is no inheritance between DefaultDocumentGeneratorConfiguration and DefaultDocumentStructureGeneratorConfiguration, in order to constraint by type the kind of generator to use the the DocumentStructureTemplate and DocumentStructure models."/>
    </eAnnotations>
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="createTemplateFileInputAccessor"
          ordered="false" lowerBound="1" eType="#//IInputFileAccessor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Return an accessor to get the template."/>
          <details key="body" value="return new org.eclipse.papyrus.model2doc.core.generatorconfiguration.internal.accessors.TemplateInputFileAccessor(this);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IDocumentGeneratorConfiguration/createTemplateFileInputAccessor"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="createDocumentOutputAccessor" ordered="false"
          lowerBound="1" eType="#//IOutputFileAccessor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Return an accessor for the generated output document."/>
          <details key="body" value="return new org.eclipse.papyrus.model2doc.core.generatorconfiguration.internal.accessors.DocumentOutputFileAccessor(this);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IDocumentGeneratorConfiguration/createDocumentOutputAccessor"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
