<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="documentstructuretemplate" nsURI="http://www.eclipse.org/papyrus/model2doc/emf/1.0.0/documentstructuretemplate"
    nsPrefix="documentstructuretemplate">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="DocumentStructureTemplate"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentTemplate" abstract="true" interface="true">
    <eOperations name="getType" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getIconPath" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticContext" ordered="false"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the element of the documented model from which the generated documentation will start."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphicalContext" ordered="false"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference the element under which the DocumentTemplate will be displayed in a TreeViewer (for example)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentTemplatePrototype"
        ordered="false" lowerBound="1" eType="#//DocumentTemplatePrototype">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference the DocumentTemplatePrototype used to initialize this DocumentTemplate."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the document. This name will be used as label in widget displaying the DocumentTemplate.&#xD;&#xA;This field won't be used in the generated document."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The description of the DocumentTemplate. &#xD;&#xA;This field is here for documentation of the DocumentStructureModel, but won't be used in the generated document."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This field will allow a better integration with the Papyrus Architecture Framework.&#xD;&#xA;The value will be something like &quot;org.eclipse.papyrus.uml.genericdocumenttemplate&quot;.&#xD;&#xA;This field will be used to find the ViewPrototype of an instance of DocumentTemplate.&#xD;&#xA;This field is useless for usage outside of Papyrus, but we set its multiplicity to [1] to avoid possible mistake in Papyrus usages."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generationConfiguration"
        ordered="false" lowerBound="1" eType="#//GenerationConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverPage" ordered="false"
        eType="#//CoverPage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentTemplatePrototype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentTemplate" ordered="false"
        lowerBound="1" eType="#//DocumentTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerationConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ouputFile" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ouputFolder" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextDocumentTemplate" eSuperTypes="#//DocumentTemplate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainTitle" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentPart" ordered="false"
        upperBound="-1" eType="#//DocumentPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentPart" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureDocumentPartTemplate"
      eSuperTypes="#//FeaturePartTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeaturePartTemplate" abstract="true"
      interface="true" eSuperTypes="#//DocumentPartTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPartTemplates" ordered="false"
        upperBound="-1" eType="#//ObjectPartTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentPartTemplate" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customTitle" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//DocumentPartTemplate">
    <eOperations name="isMatchingFilterRule" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="inputEObject" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featurePartTemplates" ordered="false"
        upperBound="-1" eType="#//FeaturePartTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassDocumentPartTemplate" eSuperTypes="#//ObjectPartTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterRule" ordered="false"
        lowerBound="1" eType="#//EClassFilterBehavior" defaultValueLiteral="TYPE_OF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EClassFilterBehavior">
    <eLiterals name="TYPE_OF"/>
    <eLiterals name="KIND_OF" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectDocumentPartTemplate" eSuperTypes="#//ObjectPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element allow to define from which specific element of a model, the documentation process must start&#xD;&#xA;This element can only be owned by a DocumentTemplate. In other case, we will return a validation error."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObject" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The field eobject is [0..1], in order to be get a valid model when we use this model as a registered template prototype and not as a final user template&#xD;&#xA;The field eobject must reference an eobject of the user model, in other case the model validation will return an error.&#xD;&#xA;&#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableOfContents" eSuperTypes="#//DocumentPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tocTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="Table Of Contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="#//DocumentPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPartTemplate" lowerBound="1"
        upperBound="-1" eType="#//ObjectPartTemplate" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
