<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="documentstructuretemplate" nsURI="http://www.eclipse.org/papyrus/model2doc/emf/1.0.0/documentstructuretemplate"
    nsPrefix="documentstructuretemplate">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="DocumentStructureTemplate"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentTemplate" abstract="true" interface="true">
    <eOperations name="getType" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getIconPath" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticContext" ordered="false"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the element of the documented model from which the generated documentation will start."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphicalContext" ordered="false"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference the element under which the DocumentTemplate will be displayed in a TreeViewer (for example)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentTemplatePrototype"
        ordered="false" lowerBound="1" eType="#//DocumentTemplatePrototype">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference the DocumentTemplatePrototype used to initialize this DocumentTemplate."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the document. This name will be used as label in widget displaying the DocumentTemplate.&#xD;&#xA;This field won't be used in the generated document."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The description of the DocumentTemplate. &#xD;&#xA;This field is here for documentation of the DocumentStructureModel, but won't be used in the generated document."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This field will allow a better integration with the Papyrus Architecture Framework.&#xD;&#xA;The value will be something like &quot;org.eclipse.papyrus.uml.genericdocumenttemplate&quot;.&#xD;&#xA;This field will be used to find the ViewPrototype of an instance of DocumentTemplate.&#xD;&#xA;This field is useless for usage outside of Papyrus, but we set its multiplicity to [1] to avoid possible mistake in Papyrus usages."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentStructureGeneratorConfiguration"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.model2doc.core.generatorconfiguration/model/generatorconfiguration.ecore#//IDocumentStructureGeneratorConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentTemplatePrototype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentTemplate" ordered="false"
        lowerBound="1" eType="#//DocumentTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextDocumentTemplate" eSuperTypes="#//DocumentTemplate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainTitle" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentPart" ordered="false"
        upperBound="-1" eType="#//DocumentPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentPart" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableOfContents" eSuperTypes="#//DocumentPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tocTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="Table Of Contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="#//DocumentPart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element represents the body of the future document. Its children describe how to traverse the user model in order to build the final document. &#xD;&#xA;Its children are an alternation of two kinds of objects: IBodyPartTemplate and ISubBodyPartTemplate. The IBodyPartTemplate children are ISubBodyPartTemplate, and in turn, the ISubBodyPartTemplate children are IBodyPartTemplate again. This occurs at each level. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyPartTemplate" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//IBodyPartTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBodyPartTemplate" abstract="true" interface="true"
      eSuperTypes="#//IBodySectionPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base element to build the body of the document."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBodySectionPartTemplate" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, we will generate something for this body part. &#xD;&#xA;If false, we will use the object to cross the user model, but we will generate nothing to this body part."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, we will generate a main title here, before to traverse the document model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customTitle" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The title to use for this section instead using the calculated one."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EClassFilterBehavior">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This enumeration allows to describe how to implement the filter rule in EClassPartTemplate."/>
    </eAnnotations>
    <eLiterals name="TYPE_OF"/>
    <eLiterals name="KIND_OF" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComposedBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//IBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This body part template can have children of type ISubBodyPartTemplate."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subBodyPartTemplate" ordered="false"
        upperBound="-1" eType="#//ISubBodyPartTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISubBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//IBodySectionPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Common interface for the children of ICompositeBodyPartTemplate."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILeafBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//IBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This body part template can't have children."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComposedSubBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//ISubBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This sub body part template can have children of type IBodyPartTemplate."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyPartTemplate" ordered="false"
        upperBound="-1" eType="#//IBodyPartTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILeafSubBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//ISubBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This sub body part template can't have children."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassPartTemplate" eSuperTypes="#//IComposedSubBodyPartTemplate">
    <eOperations name="isMatchingFilterRule" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method will return true, when the eClass field is null or if the EObject in argument match the filter behavior and false otherwise."/>
      </eAnnotations>
      <eParameters name="inputEObject" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="buildTitle" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="titleContext" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" ordered="false"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EClass used to filter EObject."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterRule" ordered="false"
        lowerBound="1" eType="#//EClassFilterBehavior" defaultValueLiteral="TYPE_OF">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Description of the way to use to filter EObject in the method isMatchingFilterRule."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferencePartTemplate" eSuperTypes="#//IComposedBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This part reference an EReference of the parent EClassPartTemplate."/>
    </eAnnotations>
    <eOperations name="buildTitle" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getMatchingReferencedEObjects" ordered="false" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the matching elements referenced by the EReference for the EObject in argument. "/>
      </eAnnotations>
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReference" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A EReference which should be provided by the EClass of the upper level."/>
        <details key="propertyEditorFactory" value="editor://documentstructuretemplate/EReferencePartTemplate/EReference/"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITemplatePartView" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This interface is used to describe BodyPartTemplate which contributes to fill the document's body."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceListView" eSuperTypes="#//EReferencePartTemplate #//ITemplatePartView"/>
</ecore:EPackage>
