<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="documentstructuretemplate" nsURI="http://www.eclipse.org/papyrus/model2doc/emf/1.0.0/documentstructuretemplate"
    nsPrefix="documentstructuretemplate">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="DocumentStructureTemplate"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentTemplate" abstract="true" interface="true">
    <eOperations name="getType" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (null != getDocumentTemplatePrototype()) {&#xA;&#x9;return getDocumentTemplatePrototype().getType();&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getIconPath" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (null != getDocumentTemplatePrototype()) {&#xA;&#x9;return getDocumentTemplatePrototype().getIconPath();&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticContext" ordered="false"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the element of the documented model from which the generated documentation will start."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphicalContext" ordered="false"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference the element under which the DocumentTemplate will be displayed in a TreeViewer (for example)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentTemplatePrototype"
        ordered="false" lowerBound="1" eType="#//DocumentTemplatePrototype">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference the DocumentTemplatePrototype used to initialize this DocumentTemplate."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the document. This name will be used as label in widget displaying the DocumentTemplate.&#xD;&#xA;This field won't be used in the generated document."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The description of the DocumentTemplate. &#xD;&#xA;This field is here for documentation of the DocumentStructureModel, but won't be used in the generated document."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This field will allow a better integration with the Papyrus Architecture Framework.&#xD;&#xA;The value will be something like &quot;org.eclipse.papyrus.uml.genericdocumenttemplate&quot;.&#xD;&#xA;This field will be used to find the ViewPrototype of an instance of DocumentTemplate.&#xD;&#xA;This field is useless for usage outside of Papyrus, but we set its multiplicity to [1] to avoid possible mistake in Papyrus usages."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentStructureGeneratorConfiguration"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.model2doc.core.generatorconfiguration/model/generatorconfiguration.ecore#//IDocumentStructureGeneratorConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.model2doc.core.author/model/author.ecore#//IAuthor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentTemplatePrototype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentTemplate" ordered="false"
        lowerBound="1" eType="#//DocumentTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextDocumentTemplate" eSuperTypes="#//DocumentTemplate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainTitle" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentPart" ordered="false"
        upperBound="-1" eType="#//DocumentPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentPart" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableOfContents" eSuperTypes="#//DocumentPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tocTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="Table Of Contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="#//DocumentPart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element represents the body of the future document. Its children describe how to traverse the user model in order to build the final document. &#xD;&#xA;Its children are an alternation of two kinds of objects: IBodyPartTemplate and ISubBodyPartTemplate. The IBodyPartTemplate children are ISubBodyPartTemplate, and in turn, the ISubBodyPartTemplate children are IBodyPartTemplate again. This occurs at each level. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyPartTemplate" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//IBodyPartTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBodyPartTemplate" abstract="true" interface="true"
      eSuperTypes="#//IBodySectionPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base element to build the body of the document."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBodySectionPartTemplate" abstract="true"
      interface="true">
    <eOperations name="buildPartTemplateTitle" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method creates the title. &#xD;&#xA;In the general case, the ISubBodyPartTemplate uses the context element to build the title, wheareas the IBodyPartTemplate don't use it."/>
        <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.operations.BodySectionPartTemplateTitleOperations.INSTANCE.buildPartTemplateTitle(this,context);"/>
      </eAnnotations>
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="generateBranch" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method allows to check if we must generate something for the context or not."/>
        <details key="body" value="if(null==context){&#xA;&#x9;return false;&#xA;}&#xA;if(null==generateBranchCondition){&#xA;&#x9;return true;&#xA;}&#xA;&#xA;return generateBranchCondition.evaluate(context);"/>
      </eAnnotations>
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, we will generate something for this body part. &#xD;&#xA;If false, we will use the object to cross the user model, but we will generate nothing to this body part."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateTitle" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, we will generate a main title here, before to traverse the document model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customTitle" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The title to use for this section instead using the calculated one."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generateBranchCondition"
        ordered="false" eType="ecore:EClass ../../org.eclipse.papyrus.infra.emf.expressions/model/expressions.ecore#//booleanexpressions/IBooleanEObjectExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When the expression returns false, nothing will be generated for the object or for its child elements."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EClassFilterBehavior">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This enumeration allows to describe how to implement the filter rule in EClassPartTemplate."/>
    </eAnnotations>
    <eLiterals name="TYPE_OF"/>
    <eLiterals name="KIND_OF" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComposedBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//IBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This body part template can have children of type ISubBodyPartTemplate."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subBodyPartTemplate" ordered="false"
        upperBound="-1" eType="#//ISubBodyPartTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISubBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//IBodySectionPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Common interface for the children of ICompositeBodyPartTemplate."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILeafBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//IBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This body part template can't have children."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComposedSubBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//ISubBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This sub body part template can have children of type IBodyPartTemplate."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyPartTemplate" ordered="false"
        upperBound="-1" eType="#//IBodyPartTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILeafSubBodyPartTemplate" abstract="true"
      interface="true" eSuperTypes="#//ISubBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This sub body part template can't have children."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassPartTemplate" eSuperTypes="#//EClassTemplate #//IComposedSubBodyPartTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClassTemplate" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract Template to represent EClasses."/>
    </eAnnotations>
    <eOperations name="isMatchingFilterRule" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method will return true, when the eClass field is null or if the EObject in argument match the filter behavior and false otherwise."/>
        <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EClassTemplateOperations.isMatchingFilterRule(this, inputEObject);"/>
      </eAnnotations>
      <eParameters name="inputEObject" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" ordered="false"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EClass used to filter EObject."/>
        <details key="propertyEditorFactory" value="editor://documentstructuretemplate/EClassTemplate/EClass/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterRule" ordered="false"
        lowerBound="1" eType="#//EClassFilterBehavior" defaultValueLiteral="TYPE_OF">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Description of the way to use to filter EObject in the method isMatchingFilterRule."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferencePartTemplate" eSuperTypes="#//EReferenceTemplate #//IComposedBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This part reference an EReference of the parent EClassPartTemplate."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceTemplate" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract Template with a EReference field and a method to get the value of a EReference for a given EObject."/>
    </eAnnotations>
    <eOperations name="getEReferenceValues" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the matching elements referenced by the EReference for the EObject in argument. "/>
        <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EReferenceTemplateOperations.getEReferenceValues(this,context);"/>
      </eAnnotations>
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="buildEReferenceValueLabel" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the label of the element given as parameter.&#xD;&#xA;The goal of this method is to return a label for each element returned by the method getEReferenceValues()"/>
        <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EReferenceTemplateOperations.buildEReferenceValueLabel(this,value);"/>
      </eAnnotations>
      <eParameters name="value" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReference" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A EReference which should be provided by the EClass of the upper level."/>
        <details key="propertyEditorFactory" value="editor://documentstructuretemplate/EReferenceTemplate/EReference/"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITemplatePartView" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This interface is used to describe BodyPartTemplate which contributes to fill the document's body."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITableView" abstract="true" interface="true"
      eSuperTypes="#//ILeafBodyPartTemplate #//ITemplatePartView">
    <eOperations name="getRows" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the elements to use as row from the context element given in parameter."/>
      </eAnnotations>
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="buildRowHeaderLabel" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method creates the label for the row header, from the rowElement given as parameter."/>
      </eAnnotations>
      <eParameters name="rowElement" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" ordered="false"
        upperBound="-1" eType="#//IColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateRowHeader" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Boolean indicating if a Row Header must be generated or not."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateColumnHeader" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Boolean indicating if a Column Header must be generated or not."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IColumn" abstract="true" interface="true">
    <eOperations name="buildColumnHeaderLabel" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the title to use for this column."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getCellValue" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the value of the cell. This value is deduced from the element represented by the column and from the row element given as parameter)."/>
      </eAnnotations>
      <eParameters name="row" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="buildCellLabel" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method creates the label from the cell value given as parameter."/>
      </eAnnotations>
      <eParameters name="cellValue" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customColumnTitle" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A custom title to use for the column."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceTableView" eSuperTypes="#//EReferenceTemplate #//ITableView">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="getRows" ordered="false" upperBound="-1"
          eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns the elements to use as row from the context element given in parameter."/>
          <details key="body" value="return getEReferenceValues(context);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//ITableView/getRows"/>
        <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="buildRowHeaderLabel" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method creates the label for the row header, from the rowElement given as parameter."/>
          <details key="body" value="return buildEReferenceValueLabel(rowElement);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//ITableView/buildRowHeaderLabel"/>
        <eParameters name="rowElement" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureColumn" eSuperTypes="#//EStructuralFeatureTemplate #//IColumn">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element allows to define a column representing an EStructuralFeature."/>
    </eAnnotations>
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="buildCellLabel" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method creates the label from the cell value given as parameter."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EStructuralFeatureColumnOperations.buildCellLabel(this,cellValue);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IColumn/buildCellLabel"/>
        <eParameters name="cellValue" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="buildColumnHeaderLabel" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns the title to use for this column."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EStructuralFeatureColumnOperations.buildColumnHeaderLabel(this);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IColumn/buildColumnHeaderLabel"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="getCellValue" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns the value of the cell. This value is deduced from the element represented by the column and from the row element given as parameter)."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EStructuralFeatureColumnOperations.getCellValue(this,row);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IColumn/getCellValue"/>
        <eParameters name="row" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureTemplate" abstract="true">
    <eOperations name="getEStructuralFeatureValues" ordered="false" upperBound="-1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the matching elements referenced by the EReference for the EObject in argument. "/>
        <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EStructuralFeatureTemplateOperations.getEStructuralFeatureValues(this,context);"/>
      </eAnnotations>
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="buildEStructuralFeatureValueLabel" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the label of the element given as parameter.&#xD;&#xA;The goal of this method is to return a label for each element returned by the method getEReferenceValues()"/>
        <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EStructuralFeatureTemplateOperations.buildEStructuralFeatureValueLabel(this,value);"/>
      </eAnnotations>
      <eParameters name="value" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The feature represented by this template"/>
        <details key="propertyEditorFactory" value="editor://documentstructuretemplate/EStructuralFeatureTemplate/EStructuralFeature/"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IListItemTemplate" abstract="true" interface="true">
    <eOperations name="buildItemLabel" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns a label for the item."/>
      </eAnnotations>
      <eParameters name="item" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getItems" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns the items for the list, according to the given context."/>
      </eAnnotations>
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateItem" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customItemLabel" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILeafListItemTemplate" abstract="true"
      interface="true" eSuperTypes="#//IRootListItemTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRootListItemTemplate" abstract="true"
      interface="true" eSuperTypes="#//IListItemTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="IComposedListItemTemplate" abstract="true"
      interface="true" eSuperTypes="#//IRootListItemTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subListItemTemplate" ordered="false"
        upperBound="-1" eType="#//ISubListItemTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISubListItemTemplate" abstract="true"
      interface="true" eSuperTypes="#//IListItemTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="IComposedSubListItemTemplate" abstract="true"
      interface="true" eSuperTypes="#//ISubListItemTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listItemTemplate" ordered="false"
        upperBound="-1" eType="#//IRootListItemTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILeafSubListItemTemplate" abstract="true"
      interface="true" eSuperTypes="#//ISubListItemTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceListItemTemplate" eSuperTypes="#//EReferenceTemplate #//IComposedListItemTemplate">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="buildItemLabel" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns a label for the item."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EReferenceListItemTemplateOperations.buildItemLabel(this,item);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IListItemTemplate/buildItemLabel"/>
        <eParameters name="item" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="getItems" ordered="false" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns the items for the list, according to the given context."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EReferenceListItemTemplateOperations.getItems(this,context);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IListItemTemplate/getItems"/>
        <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAttributeListItemTemplate" eSuperTypes="#//EAttributeTemplate #//ILeafListItemTemplate">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="buildItemLabel" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns a label for the item."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EAttributeListItemTemplateOperations.buildItemLabel(this,item);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IListItemTemplate/buildItemLabel"/>
        <eParameters name="item" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="getItems" ordered="false" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns the items for the list, according to the given context."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EAttributeListItemTemplateOperations.getItems(this,context);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IListItemTemplate/getItems"/>
        <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAttributeTemplate" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element allows to represents an EAttribute."/>
    </eAnnotations>
    <eOperations name="buildEAttributeValueLabel" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EAttributeTemplateOperations.buildEAttributeValueLabel(this, value);"/>
      </eAnnotations>
      <eParameters name="value" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getEAttributeValues" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EAttributeTemplateOperations.getEAttributeValues(this, context);"/>
      </eAnnotations>
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttribute" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassListItemTemplate" eSuperTypes="#//EClassTemplate #//IComposedSubListItemTemplate">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="getItems" ordered="false" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns the items for the list, according to the given context."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EClassListItemTemplateOperations.getItems(this,context);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IListItemTemplate/getItems"/>
        <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="buildItemLabel" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns a label for the item."/>
          <details key="body" value="return org.eclipse.papyrus.model2doc.emf.documentstructuretemplate.internal.operations.EClassListItemTemplateOperations.buildItemLabel(this,item);"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//IListItemTemplate/buildItemLabel"/>
        <eParameters name="item" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeListView" eSuperTypes="#//ILeafBodyPartTemplate #//ITemplatePartView">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element allows to represent a list with several level."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootListItemTemplate" ordered="false"
        upperBound="-1" eType="#//IRootListItemTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsertFileTemplate" eSuperTypes="../../org.eclipse.papyrus.model2doc.core.builtintypes/model/BuiltInTypes.ecore#//DefaultFileReference #//ILeafSubBodyPartTemplate #//ILeafBodyPartTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element allows to insert the content of an existing file into the generated file."/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
